sudo: no
language: python
install:
  - pip install tox coveralls
script:
  - tox
env:
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=py26
  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=py27
#  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=py32
#  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=py33
#  - PIP_DOWNLOAD_CACHE=pip_cache TOXENV=py34
after_success: coveralls
cache:
  directories:
    - pip_cache
branches:
  only:
    - develop
