VERSION = '0.1'

DEBUG_MODE_BRIEF = "brief"
DEBUG_MODE_SILENT = "silent"
DEBUG_MODE_VERBOSE = "verbose"

PAYMENT_METHOD_CARD = "card"
PAYMENT_METHOD_BANK = "bank"
PAYMENT_METHOD_PHONE = "phone"
PAYMENT_METHOD_INVOICE = "invoice"
